name: Build and Release Documentation

on:
  push:
    tags:
      - "v*"  # Trigger the workflow when a new version tag is pushed

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assuming you have a requirements file with sphinx and dependencies

      - name: Build PDF documentation
        run: |
          sphinx-build -b pdf src/users_guide build/pdf  

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: documentation-pdf
          path: build/pdf/*.pdf  # Adjust if your output file has a different name or location

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download PDF artifact
        uses: actions/download-artifact@v2
        with:
          name: documentation-pdf  # This will download the artifact from the previous step

      - name: Create Release and Upload PDF
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/pdf/*.pdf  # Uploads the PDF to the release
          tag: ${{ github.ref }}
